use anyhow::Result;
use ranvier_core::schematic::Schematic;

pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, schematic: &Schematic) -> Result<String> {
        let mut ts = String::new();

        ts.push_str("// Generated by Ranvier Synapse\n");
        ts.push_str(&format!("// Schematic: {}\n\n", schematic.name));

        ts.push_str("export namespace Schematic {\n");

        for node in &schematic.nodes {
            let safe_label = node.label.replace(" ", "_").replace("::", "__");

            ts.push_str(&format!("  export namespace {} {{\n", safe_label));
            ts.push_str(&format!(
                "    export type Input = {};\n",
                self.map_type(&node.input_type)
            ));
            ts.push_str(&format!(
                "    export type Output = {};\n",
                self.map_type(&node.output_type)
            ));
            ts.push_str("  }\n\n");
        }

        ts.push_str("}\n");

        Ok(ts)
    }

    fn map_type(&self, rust_type: &str) -> String {
        // Basic heuristic for Rust -> TS mapping
        match rust_type {
            t if t.contains("String") || t.contains("str") => "string".to_string(),
            t if t.contains("u32")
                || t.contains("i32")
                || t.contains("f64")
                || t.contains("usize") =>
            {
                "number".to_string()
            }
            t if t.contains("bool") => "boolean".to_string(),
            "()" => "void".to_string(),
            t if t.starts_with("Option<") => {
                let inner = t.trim_start_matches("Option<").trim_end_matches(">");
                format!("{} | null", self.map_type(inner))
            }
            t if t.starts_with("Vec<") => {
                let inner = t.trim_start_matches("Vec<").trim_end_matches(">");
                format!("Array<{}>", self.map_type(inner))
            }
            _ => "any".to_string(), // Fallback for complex structs (TODO: improved reflection)
        }
    }
}
