// Generated by Ranvier Synapse
// Schematic: My First Schematic

export namespace Schematic {
  export namespace My_First_Schematic {
    export type Input = any;
    export type Output = void;
  }

  export namespace LogStart {
    export type Input = void;
    export type Output = string;
  }

  export namespace ProcessData {
    export type Input = string;
    export type Output = string;
  }

  export namespace LogEnd {
    export type Input = string;
    export type Output = void;
  }

}
