#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(scriptDir, '..');
const inventoryPath = path.join(workspaceRoot, 'api-surface-inventory.json');
const baselinePath = path.join(workspaceRoot, 'api-stable-candidate-baseline.json');
const mode = process.argv[2] ?? '--check';

if (!['--write', '--check'].includes(mode)) {
  console.error('usage: node scripts/candidate_api_baseline.mjs [--write|--check]');
  process.exit(2);
}

function canonicalText(value) {
  return value.toString('utf8').replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
}

function readJson(file) {
  return JSON.parse(canonicalText(readFileSync(file)));
}

function cargoMetadata() {
  const result = spawnSync('cargo', ['metadata', '--no-deps', '--format-version', '1'], {
    cwd: workspaceRoot,
    encoding: 'utf8'
  });
  if ((result.status ?? 1) !== 0) {
    throw new Error(result.stderr?.trim() || 'cargo metadata failed');
  }
  return JSON.parse(result.stdout);
}

function stableItems(productCrate) {
  return productCrate.items
    .filter((item) => item.stability === 'Stable Candidate')
    .map((item) => ({
      path: item.path,
      kind: item.kind,
      origin: item.origin,
      target: item.target,
      owner: item.owner,
      boundary: item.boundary
    }))
    .sort((left, right) => left.path.localeCompare(right.path) || left.kind.localeCompare(right.kind));
}

function buildBaseline(inventory, metadata) {
  const crates = inventory.crates
    .map((productCrate) => ({
      package: productCrate.package,
      features: [...productCrate.features].sort(),
      items: stableItems(productCrate)
    }))
    .filter((productCrate) => productCrate.items.length > 0)
    .sort((left, right) => left.package.localeCompare(right.package));
  const itemCount = crates.reduce((total, productCrate) => total + productCrate.items.length, 0);
  const candidatePackages = crates.map((productCrate) => productCrate.package);
  const packagesByName = new Map(metadata.packages.map((pkg) => [pkg.name, pkg]));
  const cargoSemverPackages = candidatePackages.filter((packageName) =>
    packagesByName.get(packageName)?.targets.some((target) => target.kind.includes('lib'))
  );

  return {
    schema_version: '1.0.0',
    _generated: {
      notice: 'Generated by scripts/candidate_api_baseline.mjs; update only through reviewed --write.',
      exact_scope: 'Stable Candidate item identity, ownership, re-export target, and typed/runtime boundary.',
      semver_scope: 'cargo-semver-checks runs on every candidate-bearing crate as a conservative whole-crate superset.'
    },
    product_version: inventory.product_version,
    baseline_ref: 'v0.51.0',
    baseline_commit: '3578799759da5d2fb3ad5742b67b7c281b726754',
    cargo_semver_feature_mode: 'all-features',
    stable_candidate_item_count: itemCount,
    candidate_bearing_packages: candidatePackages,
    cargo_semver_packages: cargoSemverPackages,
    compile_only_packages: candidatePackages.filter((packageName) => !cargoSemverPackages.includes(packageName)),
    crates
  };
}

const expected = `${JSON.stringify(buildBaseline(readJson(inventoryPath), cargoMetadata()), null, 2)}\n`;
if (mode === '--write') {
  writeFileSync(baselinePath, expected, 'utf8');
  const baseline = JSON.parse(expected);
  console.log(`wrote api-stable-candidate-baseline.json (${baseline.stable_candidate_item_count} items, ${baseline.candidate_bearing_packages.length} candidate crates, ${baseline.cargo_semver_packages.length} semver crates)`);
} else {
  let actual;
  try {
    actual = canonicalText(readFileSync(baselinePath));
  } catch {
    console.error('candidate API baseline is missing; run with --write and review the result');
    process.exit(1);
  }
  if (actual !== expected) {
    console.error('candidate API baseline drifted; do not rewrite it without SemVer and migration review');
    process.exit(1);
  }
  const baseline = JSON.parse(expected);
  console.log(`candidate API baseline: current (${baseline.stable_candidate_item_count} items, ${baseline.candidate_bearing_packages.length} candidate crates, ${baseline.cargo_semver_packages.length} semver crates)`);
}
